# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/haruspex',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/haruspex',
                'lib_path': 'haruspex'},
  'syms': { 'haruspex.haruspex': {'haruspex.haruspex.HaruspexModel': ('haruspex_model.html#haruspexmodel', 'haruspex/haruspex.py')},
            'haruspex.utils.data_loading': { 'haruspex.utils.data_loading.DataLoader': ( 'utils/data_loading.html#dataloader',
                                                                                         'haruspex/utils/data_loading.py'),
                                             'haruspex.utils.data_loading.DataLoader.__init__': ( 'utils/data_loading.html#dataloader.__init__',
                                                                                                  'haruspex/utils/data_loading.py')}}}
