"""Haruspex is a model for media mixed modeling and predicting performance of media plans"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_haruspex_model.ipynb.

# %% auto 0
__all__ = ['HaruspexModel']

# %% ../nbs/00_haruspex_model.ipynb 3
class HaruspexModel:
    ...
